"""create stations, parameters and observations

Revision ID: a30731568552
Revises:
Create Date: 2026-09-29 17:34:16.747625
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a30731568552"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameters",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_parameters")),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("municipality", sa.String(length=100), nullable=False),
        sa.Column("province", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stations")),
    )
    op.create_index(op.f("ix_stations_municipality"), "stations", ["municipality"], unique=False)
    op.create_index(op.f("ix_stations_province"), "stations", ["province"], unique=False)
    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("parameter_code", sa.String(length=50), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("validation_code", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parameter_code"],
            ["parameters.code"],
            name=op.f("fk_observations_parameter_code_parameters"),
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["stations.id"], name=op.f("fk_observations_station_id_stations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint(
            "station_id",
            "observed_at",
            "parameter_code",
            name=op.f("uq_observations_station_id_observed_at_parameter_code"),
        ),
    )
    op.create_index(
        op.f("ix_observations_observed_at"), "observations", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_observations_parameter_code"), "observations", ["parameter_code"], unique=False
    )
    op.create_index(
        op.f("ix_observations_station_id"), "observations", ["station_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_station_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_parameter_code"), table_name="observations")
    op.drop_index(op.f("ix_observations_observed_at"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_stations_province"), table_name="stations")
    op.drop_index(op.f("ix_stations_municipality"), table_name="stations")
    op.drop_table("stations")
    op.drop_table("parameters")
    # ### end Alembic commands ###
